---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-k8s-deployment
spec:
  selector:
    matchLabels:
      app: flask-k8s
  template:
    metadata:
      labels:
        app: flask-k8s
    spec:
      containers:
        - name: flask-k8s
          image: docker.io/randilt/flask_app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-k8s-service
spec:
  selector:
    app: flask-k8s
  ports:
    - protocol: "TCP"
      port: 8000
      targetPort: 5000
  type: LoadBalancer
