apiVersion: apps/v1
kind: Deployment
# A deployment creates a replicaset from pods
metadata:
  name: frontend
  labels:
    app: flask
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
      tier: frontend
  # The template tells you what pods are used inside the deployment
  template:
    metadata:
      labels:
        app: flask
        tier: frontend
    spec:
      # This tells you what docker container should be running inside a pod
      containers:
      - name: flask
        image: mrasap/flask
        ports:
        - containerPort: 8080
        # These probes are used to check whether it is still alive
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
  labels:
    app: flask
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  # The selector tells the service on which deployment it should be applied
  selector:
    app: flask
    tier: frontend